#!/bin/bash
set -euo pipefail
# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook starting"
docker build --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
             --build-arg VCS_REF="$(git rev-parse --short=10 HEAD)" \
             -t "$IMAGE_NAME" "$@" .